name: Update mk-ca-bundle.pl script

on:
  schedule:
    - cron: "14 15 * * *"
  workflow_dispatch:

jobs:
  update-mk-ca-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Auth Token
        id: auth-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.auth-token.outputs.token }}
      - name: Update mk-ca-bundle.pl script
        run: |
          ./maint/update-mk-ca-bundle
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.auth-token.outputs.token }}
          commit-message: Update mk-ca-bundle.pl script
          title: Update mk-ca-bundle.pl script
          branch: update-mk-ca-bundle
