name: Update cacert.pem file

on:
  schedule:
    - cron: "33 16 * * *"
  workflow_dispatch:

jobs:
  update-cacert-file:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Auth Token
        id: auth-token
        uses: jamestrousdale/github-app-jwt-token@0.1.4
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - id: git-user
        name: Set up git user
        uses: haarg/setup-git-user@v1
        with:
          jwt: ${{ steps.auth-token.outputs.jwt }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.auth-token.outputs.access-token }}
      - name: Update cacert.pem file
        run: |
          ./maint/update-cacert-file
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.auth-token.outputs.access-token }}
          commit-message: Update certificate bundle
          author: ${{ steps.git-user.outputs.user-full }}
          committer: ${{ steps.git-user.outputs.user-full }}
          title: Update certificate bundle
          branch: update-cacert-file
